### PR TITLE
tor is inside net-vpn

### PR DESCRIPTION
**Pull request by phieber**

### CODE REVIEW

**Comment by hasufell** [comment]
Needs a revbump.

**Comment by phieber** [comment]
switched to latest version

**Comment by hasufell** [comment]
I don't know what you did there. I didn't say you should replace the patchlevel with revision. I said you should do a revbump. The correct filename would have been `onioncat-0.2.2_p569-r1.ebuild`, so the changed dependencies get recorded into the VDB by reinstalling.

**Comment by phieber** [comment]
I know but as there is a new onioncat release, I decided to change the release as this would also change the dependency

**Pull request merged**
